<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\NonUniqueResultException;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param User $user
     * @return \Doctrine\ORM\Query
     */
    public function findAllTodoByUser(User $user)
    {
        return $this->createQueryBuilder('todo')
            ->andWhere('todo.user = :user')
            ->setParameter('user', $user)
            ->getQuery();
    }

    /**
     * @param User $user
     * @return mixed
     */
    public function findAllUserTodo(User $user)
    {
        try {
            return $this->createQueryBuilder('todo')
                ->andWhere('todo.user = :user')
                ->setParameter('user', $user)
                ->getQuery()
                ->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {

        }
    }

    /**
     * @param User $user
     * @param $todoID
     * @return mixed
     */
    public function findByUserAndTodo(User $user, $todoID)
    {
        try {
            return $this->createQueryBuilder('todo')
                ->andWhere('todo.user = :user', 'todo.id = :id')
                ->setParameter('user', $user)
                ->setParameter('id', $todoID)
                ->getQuery()
                ->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {

        }
    }
}
