AppBundle\Entity\Task:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TaskRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        deadline:
            type: datetime
        priority:
            type: string
            length: '100'
        status:
            type: string
            length: 10
    manyToOne:
        todo:
            targetEntity: Todo
            inversedBy: tasks
            joinColumn:
                name: todo_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
