AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            column: firstname
            type: string
            length: 40
        lastName:
            column: lastname
            type: string
            length: 50
        displayName:
            column: display_name
            type: string
            length: 40
    oneToMany:
        todos:
            targetEntity: Todo
            mappedBy: user

